 export class PokemonNamesAndImages {
    pokemons = [
{ id: 1,
  name: 'Bulbasaur',
  imagePath: 'assets/pokemon/001Bulbasaur.png' },
{ id: 2, name: 'Ivysaur', imagePath: 'assets/pokemon/002Ivysaur.png' },
{ id: 3,
  name: 'Venusaur',
  imagePath: 'assets/pokemon/003Venusaur.png' },
{ id: 4,
  name: 'Charmander',
  imagePath: 'assets/pokemon/004Charmander.png' },
{ id: 5,
  name: 'Charmeleon',
  imagePath: 'assets/pokemon/005Charmeleon.png' },
{ id: 6,
  name: 'Charizard',
  imagePath: 'assets/pokemon/006Charizard.png' },
{ id: 7,
  name: 'Squirtle',
  imagePath: 'assets/pokemon/007Squirtle.png' },
{ id: 8,
  name: 'Wartortle',
  imagePath: 'assets/pokemon/008Wartortle.png' },
{ id: 9,
  name: 'Blastoise',
  imagePath: 'assets/pokemon/009Blastoise.png' },
{ id: 10,
  name: 'Caterpie',
  imagePath: 'assets/pokemon/010Caterpie.png' },
{ id: 11,
  name: 'Metapod',
  imagePath: 'assets/pokemon/011Metapod.png' },
{ id: 12,
  name: 'Butterfree',
  imagePath: 'assets/pokemon/012Butterfree.png' },
{ id: 13, name: 'Weedle', imagePath: 'assets/pokemon/013Weedle.png' },
{ id: 14, name: 'Kakuna', imagePath: 'assets/pokemon/014Kakuna.png' },
{ id: 15,
  name: 'Beedrill',
  imagePath: 'assets/pokemon/015Beedrill.png' },
{ id: 16, name: 'Pidgey', imagePath: 'assets/pokemon/016Pidgey.png' },
{ id: 17,
  name: 'Pidgeotto',
  imagePath: 'assets/pokemon/017Pidgeotto.png' },
{ id: 18,
  name: 'Pidgeot',
  imagePath: 'assets/pokemon/018Pidgeot.png' },
{ id: 19,
  name: 'Rattata',
  imagePath: 'assets/pokemon/019Rattata.png' },
{ id: 20,
  name: 'Raticate',
  imagePath: 'assets/pokemon/020Raticate.png' },
{ id: 21,
  name: 'Spearow',
  imagePath: 'assets/pokemon/021Spearow.png' },
{ id: 22, name: 'Fearow', imagePath: 'assets/pokemon/022Fearow.png' },
{ id: 23, name: 'Ekans', imagePath: 'assets/pokemon/023Ekans.png' },
{ id: 24, name: 'Arbok', imagePath: 'assets/pokemon/024Arbok.png' },
{ id: 25,
  name: 'Pikachu',
  imagePath: 'assets/pokemon/025Pikachu.png' },
{ id: 26, name: 'Raichu', imagePath: 'assets/pokemon/026Raichu.png' },
{ id: 27,
  name: 'Sandshrew',
  imagePath: 'assets/pokemon/027Sandshrew.png' },
{ id: 28,
  name: 'Sandslash',
  imagePath: 'assets/pokemon/028Sandslash.png' },
{ id: 29,
  name: 'Nidoran',
  imagePath: 'assets/pokemon/029Nidoran.png' },
{ id: 30,
  name: 'Nidorina',
  imagePath: 'assets/pokemon/030Nidorina.png' },
{ id: 31,
  name: 'Nidoqueen',
  imagePath: 'assets/pokemon/031Nidoqueen.png' },
{ id: 32,
  name: 'Nidoran',
  imagePath: 'assets/pokemon/032Nidoran.png' },
{ id: 33,
  name: 'Nidorino',
  imagePath: 'assets/pokemon/033Nidorino.png' },
{ id: 34,
  name: 'Nidoking',
  imagePath: 'assets/pokemon/034Nidoking.png' },
{ id: 35,
  name: 'Clefairy',
  imagePath: 'assets/pokemon/035Clefairy.png' },
{ id: 36,
  name: 'Clefable',
  imagePath: 'assets/pokemon/036Clefable.png' },
{ id: 37, name: 'Vulpix', imagePath: 'assets/pokemon/037Vulpix.png' },
{ id: 38,
  name: 'Ninetales',
  imagePath: 'assets/pokemon/038Ninetales.png' },
{ id: 39,
  name: 'Jigglypuff',
  imagePath: 'assets/pokemon/039Jigglypuff.png' },
{ id: 40,
  name: 'Wigglytuff',
  imagePath: 'assets/pokemon/040Wigglytuff.png' },
{ id: 41, name: 'Zubat', imagePath: 'assets/pokemon/041Zubat.png' },
{ id: 42, name: 'Golbat', imagePath: 'assets/pokemon/042Golbat.png' },
{ id: 43, name: 'Oddish', imagePath: 'assets/pokemon/043Oddish.png' },
{ id: 44, name: 'Gloom', imagePath: 'assets/pokemon/044Gloom.png' },
{ id: 45,
  name: 'Vileplume',
  imagePath: 'assets/pokemon/045Vileplume.png' },
{ id: 46, name: 'Paras', imagePath: 'assets/pokemon/046Paras.png' },
{ id: 47,
  name: 'Parasect',
  imagePath: 'assets/pokemon/047Parasect.png' },
{ id: 48,
  name: 'Venonat',
  imagePath: 'assets/pokemon/048Venonat.png' },
{ id: 49,
  name: 'Venomoth',
  imagePath: 'assets/pokemon/049Venomoth.png' },
{ id: 50,
  name: 'Diglett',
  imagePath: 'assets/pokemon/050Diglett.png' },
{ id: 51,
  name: 'Dugtrio',
  imagePath: 'assets/pokemon/051Dugtrio.png' },
{ id: 52, name: 'Meowth', imagePath: 'assets/pokemon/052Meowth.png' },
{ id: 53,
  name: 'Persian',
  imagePath: 'assets/pokemon/053Persian.png' },
{ id: 54,
  name: 'Psyduck',
  imagePath: 'assets/pokemon/054Psyduck.png' },
{ id: 55,
  name: 'Golduck',
  imagePath: 'assets/pokemon/055Golduck.png' },
{ id: 56, name: 'Mankey', imagePath: 'assets/pokemon/056Mankey.png' },
{ id: 57,
  name: 'Primeape',
  imagePath: 'assets/pokemon/057Primeape.png' },
{ id: 58,
  name: 'Growlithe',
  imagePath: 'assets/pokemon/058Growlithe.png' },
{ id: 59,
  name: 'Arcanine',
  imagePath: 'assets/pokemon/059Arcanine.png' },
{ id: 60,
  name: 'Poliwag',
  imagePath: 'assets/pokemon/060Poliwag.png' },
{ id: 61,
  name: 'Poliwhirl',
  imagePath: 'assets/pokemon/061Poliwhirl.png' },
{ id: 62,
  name: 'Poliwrath',
  imagePath: 'assets/pokemon/062Poliwrath.png' },
{ id: 63, name: 'Abra', imagePath: 'assets/pokemon/063Abra.png' },
{ id: 64,
  name: 'Kadabra',
  imagePath: 'assets/pokemon/064Kadabra.png' },
{ id: 65,
  name: 'Alakazam',
  imagePath: 'assets/pokemon/065Alakazam.png' },
{ id: 66, name: 'Machop', imagePath: 'assets/pokemon/066Machop.png' },
{ id: 67,
  name: 'Machoke',
  imagePath: 'assets/pokemon/067Machoke.png' },
{ id: 68,
  name: 'Machamp',
  imagePath: 'assets/pokemon/068Machamp.png' },
{ id: 69,
  name: 'Bellsprout',
  imagePath: 'assets/pokemon/069Bellsprout.png' },
{ id: 70,
  name: 'Weepinbell',
  imagePath: 'assets/pokemon/070Weepinbell.png' },
{ id: 71,
  name: 'Victreebel',
  imagePath: 'assets/pokemon/071Victreebel.png' },
{ id: 72,
  name: 'Tentacool',
  imagePath: 'assets/pokemon/072Tentacool.png' },
{ id: 73,
  name: 'Tentacruel',
  imagePath: 'assets/pokemon/073Tentacruel.png' },
{ id: 74,
  name: 'Geodude',
  imagePath: 'assets/pokemon/074Geodude.png' },
{ id: 75,
  name: 'Graveler',
  imagePath: 'assets/pokemon/075Graveler.png' },
{ id: 76, name: 'Golem', imagePath: 'assets/pokemon/076Golem.png' },
{ id: 77, name: 'Ponyta', imagePath: 'assets/pokemon/077Ponyta.png' },
{ id: 78,
  name: 'Rapidash',
  imagePath: 'assets/pokemon/078Rapidash.png' },
{ id: 79,
  name: 'Slowpoke',
  imagePath: 'assets/pokemon/079Slowpoke.png' },
{ id: 80,
  name: 'Slowbro',
  imagePath: 'assets/pokemon/080Slowbro.png' },
{ id: 81,
  name: 'Magnemite',
  imagePath: 'assets/pokemon/081Magnemite.png' },
{ id: 82,
  name: 'Magneton',
  imagePath: 'assets/pokemon/082Magneton.png' },
{ id: 83,
  name: 'Farfetchd',
  imagePath: 'assets/pokemon/083Farfetchd.png' },
{ id: 84, name: 'Doduo', imagePath: 'assets/pokemon/084Doduo.png' },
{ id: 85, name: 'Dodrio', imagePath: 'assets/pokemon/085Dodrio.png' },
{ id: 86, name: 'Seel', imagePath: 'assets/pokemon/086Seel.png' },
{ id: 87,
  name: 'Dewgong',
  imagePath: 'assets/pokemon/087Dewgong.png' },
{ id: 88, name: 'Grimer', imagePath: 'assets/pokemon/088Grimer.png' },
{ id: 89, name: 'Muk', imagePath: 'assets/pokemon/089Muk.png' },
{ id: 90,
  name: 'Shellder',
  imagePath: 'assets/pokemon/090Shellder.png' },
{ id: 91,
  name: 'Cloyster',
  imagePath: 'assets/pokemon/091Cloyster.png' },
{ id: 92, name: 'Gastly', imagePath: 'assets/pokemon/092Gastly.png' },
{ id: 93,
  name: 'Haunter',
  imagePath: 'assets/pokemon/093Haunter.png' },
{ id: 94, name: 'Gengar', imagePath: 'assets/pokemon/094Gengar.png' },
{ id: 95, name: 'Onix', imagePath: 'assets/pokemon/095Onix.png' },
{ id: 96,
  name: 'Drowzee',
  imagePath: 'assets/pokemon/096Drowzee.png' },
{ id: 97, name: 'Hypno', imagePath: 'assets/pokemon/097Hypno.png' },
{ id: 98, name: 'Krabby', imagePath: 'assets/pokemon/098Krabby.png' },
{ id: 99,
  name: 'Kingler',
  imagePath: 'assets/pokemon/099Kingler.png' },
{ id: 100,
  name: 'Voltorb',
  imagePath: 'assets/pokemon/100Voltorb.png' },
{ id: 101,
  name: 'Electrode',
  imagePath: 'assets/pokemon/101Electrode.png' },
{ id: 102,
  name: 'Exeggcute',
  imagePath: 'assets/pokemon/102Exeggcute.png' },
{ id: 103,
  name: 'Exeggutor',
  imagePath: 'assets/pokemon/103Exeggutor.png' },
{ id: 104, name: 'Cubone', imagePath: 'assets/pokemon/104Cubone.png' },
{ id: 105,
  name: 'Marowak',
  imagePath: 'assets/pokemon/105Marowak.png' },
{ id: 106,
  name: 'Hitmonlee',
  imagePath: 'assets/pokemon/106Hitmonlee.png' },
{ id: 107,
  name: 'Hitmonchan',
  imagePath: 'assets/pokemon/107Hitmonchan.png' },
{ id: 108,
  name: 'Lickitung',
  imagePath: 'assets/pokemon/108Lickitung.png' },
{ id: 109,
  name: 'Koffing',
  imagePath: 'assets/pokemon/109Koffing.png' },
{ id: 110,
  name: 'Weezing',
  imagePath: 'assets/pokemon/110Weezing.png' },
{ id: 111,
  name: 'Rhyhorn',
  imagePath: 'assets/pokemon/111Rhyhorn.png' },
{ id: 112, name: 'Rhydon', imagePath: 'assets/pokemon/112Rhydon.png' },
{ id: 113,
  name: 'Chansey',
  imagePath: 'assets/pokemon/113Chansey.png' },
{ id: 114,
  name: 'Tangela',
  imagePath: 'assets/pokemon/114Tangela.png' },
{ id: 115,
  name: 'Kangaskhan',
  imagePath: 'assets/pokemon/115Kangaskhan.png' },
{ id: 116, name: 'Horsea', imagePath: 'assets/pokemon/116Horsea.png' },
{ id: 117, name: 'Seadra', imagePath: 'assets/pokemon/117Seadra.png' },
{ id: 118,
  name: 'Goldeen',
  imagePath: 'assets/pokemon/118Goldeen.png' },
{ id: 119,
  name: 'Seaking',
  imagePath: 'assets/pokemon/119Seaking.png' },
{ id: 120, name: 'Staryu', imagePath: 'assets/pokemon/120Staryu.png' },
{ id: 121,
  name: 'Starmie',
  imagePath: 'assets/pokemon/121Starmie.png' },
{ id: 122,
  name: 'Mr_Mime',
  imagePath: 'assets/pokemon/122Mr_Mime.png' },
{ id: 123,
  name: 'Scyther',
  imagePath: 'assets/pokemon/123Scyther.png' },
{ id: 124, name: 'Jynx', imagePath: 'assets/pokemon/124Jynx.png' },
{ id: 125,
  name: 'Electabuzz',
  imagePath: 'assets/pokemon/125Electabuzz.png' },
{ id: 126, name: 'Magmar', imagePath: 'assets/pokemon/126Magmar.png' },
{ id: 127, name: 'Pinsir', imagePath: 'assets/pokemon/127Pinsir.png' },
{ id: 128, name: 'Tauros', imagePath: 'assets/pokemon/128Tauros.png' },
{ id: 129,
  name: 'Magikarp',
  imagePath: 'assets/pokemon/129Magikarp.png' },
{ id: 130,
  name: 'Gyarados',
  imagePath: 'assets/pokemon/130Gyarados.png' },
{ id: 131, name: 'Lapras', imagePath: 'assets/pokemon/131Lapras.png' },
{ id: 132, name: 'Ditto', imagePath: 'assets/pokemon/132Ditto.png' },
{ id: 133, name: 'Eevee', imagePath: 'assets/pokemon/133Eevee.png' },
{ id: 134,
  name: 'Vaporeon',
  imagePath: 'assets/pokemon/134Vaporeon.png' },
{ id: 135,
  name: 'Jolteon',
  imagePath: 'assets/pokemon/135Jolteon.png' },
{ id: 136,
  name: 'Flareon',
  imagePath: 'assets/pokemon/136Flareon.png' },
{ id: 137,
  name: 'Porygon',
  imagePath: 'assets/pokemon/137Porygon.png' },
{ id: 138,
  name: 'Omanyte',
  imagePath: 'assets/pokemon/138Omanyte.png' },
{ id: 139,
  name: 'Omastar',
  imagePath: 'assets/pokemon/139Omastar.png' },
{ id: 140, name: 'Kabuto', imagePath: 'assets/pokemon/140Kabuto.png' },
{ id: 141,
  name: 'Kabutops',
  imagePath: 'assets/pokemon/141Kabutops.png' },
{ id: 142,
  name: 'Aerodactyl',
  imagePath: 'assets/pokemon/142Aerodactyl.png' },
{ id: 143,
  name: 'Snorlax',
  imagePath: 'assets/pokemon/143Snorlax.png' },
{ id: 144,
  name: 'Articuno',
  imagePath: 'assets/pokemon/144Articuno.png' },
{ id: 145, name: 'Zapdos', imagePath: 'assets/pokemon/145Zapdos.png' },
{ id: 146,
  name: 'Moltres',
  imagePath: 'assets/pokemon/146Moltres.png' },
{ id: 147,
  name: 'Dratini',
  imagePath: 'assets/pokemon/147Dratini.png' },
{ id: 148,
  name: 'Dragonair',
  imagePath: 'assets/pokemon/148Dragonair.png' },
{ id: 149,
  name: 'Dragonite',
  imagePath: 'assets/pokemon/149Dragonite.png' },
{ id: 150, name: 'Mewtwo', imagePath: 'assets/pokemon/150Mewtwo.png' },
{ id: 151, name: 'Mew', imagePath: 'assets/pokemon/151Mew.png' }

];

getAllPokemonData(){
    return this.pokemons.slice();
}
    

 }